### ISSUE TITLE
Spectrogram quality 

### ISSUE THREAD

**Issue by JuanFMontesinos** [pseeth/torch-stft#5]
Hi,
I've testing your code and it reconstruct your stft.
I'm afraid this is librosa stft
![image](https://user-images.githubusercontent.com/32466310/51270087-5d3bdf00-19c4-11e9-806a-0905bfa9ce01.png)

And this is the spectrogram computed with this method
![image](https://user-images.githubusercontent.com/32466310/51270121-6fb61880-19c4-11e9-9deb-00764917463e.png)

**Comment by JuanFMontesinos** [comment]
Well, to be constructive you can fix it with the hanning window from scipy
scipy.signal.get_window("hanning", nfft)

**Comment by Jonghu** [comment]
Hi, @JuanFMontesinos 
Could you tell me how you applied window at the code please? :)

**Comment by pseeth** [comment]
These should be the same now, within some margin of error. Still having an issue with getting the phases to match perfectly though.
