### ISSUE TITLE
wrong mel convertion

### ISSUE THREAD

**Issue by Andras7** [pseeth/torch-stft#6]
this line robbed me: `mel_spectrogram = F.linear(magnitude.transpose(-1, -2), self.mel_filter_bank)`

instead we should use this:  `torch.bmm(self.mel_filter_bank.expand(input_data.size(0), -1, -1), magnitude).transpose(1, 2)`

**Comment by pseeth** [comment]
Decided this was a little out of scope for this package anyway. Just want it to be a hopefully well-tested and functioning differentiable STFT, so I removed that layer. If you're still looking for this though, here's one that works for me: https://github.com/interactiveaudiolab/nussl/blob/clustering/nussl/deep/networks/modules.py#L9
